workflows:
  android-app:
    name: Build Android APK
    environment:
      android: true
    scripts:
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/**/*.apk

