workflows:
  android-app:
    name: Android Debug APK Build
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    cache:
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
