workflows:
  android-app:
    name: Android Debug APK Build
    environment:
      java: 17
      cache:
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
