workflows:
  android-workflow:
    name: Build Android APK
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Set up Android SDK
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0"
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
